language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false
#script: # use the default script which does the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("SuffixArrays")'
