name = "SuffixArrays"
uuid = "24f65c1e-0a10-5d3d-8a1f-a83399f3fced"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>", "Stefan Karpinski <stefan@karpinski.org>"]
version = "1.0.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
